baseURL = "http://opereon.io"
languageCode = "en-us"
title = "Opereon"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 2

[params]
google_analytics_id=""

[params.logo]
mobile = "/images/logo.svg"
standard  = "/images/logo.svg"
