baseURL = "https://opereon.io"
languageCode = "en-us"
title = "Opereon"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "swapoff"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Documentation"
url = "/docs/"
weight = 2

[[menu.icon]]
url = "https://github.com/opereon"
name = "fab fa-github"
weight = 1

[params]
mainSections = ["docs"]
google_analytics_id = ""
homepage_button_link = "/docs"
homepage_button_text = "Get started"
homepage_intro = """
Opereon is an easy tool for maintaining multiple server hosts in one platform.
Packed to the gills with amazing features and tools, coupled with heaps of detailed documentation, OPEREON will make you look like a hero server hosts manager!
"""

[params.logo]
mobile = "/images/logo.svg"
standard  = "/images/logo.svg"

# Topics
[params.topics]
title = "Why Opereon"
